<?php
/**
 * CustomFieldValueTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PracticePanther KISS Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CustomFieldValueTest Class Doc Comment
 *
 * @category    Class */
// * @description CustomFieldValue
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CustomFieldValueTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CustomFieldValue"
     */
    public function testCustomFieldValue()
    {
    }

    /**
     * Test attribute "custom_field_ref"
     */
    public function testPropertyCustomFieldRef()
    {
    }

    /**
     * Test attribute "value_boolean"
     */
    public function testPropertyValueBoolean()
    {
    }

    /**
     * Test attribute "contact_ref"
     */
    public function testPropertyContactRef()
    {
    }

    /**
     * Test attribute "value_date_time"
     */
    public function testPropertyValueDateTime()
    {
    }

    /**
     * Test attribute "value_number"
     */
    public function testPropertyValueNumber()
    {
    }

    /**
     * Test attribute "value_string"
     */
    public function testPropertyValueString()
    {
    }
}
