<?php
/**
 * InvoiceLineItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PracticePanther KISS Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InvoiceLineItemTest Class Doc Comment
 *
 * @category    Class */
// * @description InvoiceLineItem
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InvoiceLineItemTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InvoiceLineItem"
     */
    public function testInvoiceLineItem()
    {
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
    }

    /**
     * Test attribute "rate"
     */
    public function testPropertyRate()
    {
    }

    /**
     * Test attribute "discount"
     */
    public function testPropertyDiscount()
    {
    }

    /**
     * Test attribute "subtotal"
     */
    public function testPropertySubtotal()
    {
    }

    /**
     * Test attribute "tax1_name"
     */
    public function testPropertyTax1Name()
    {
    }

    /**
     * Test attribute "tax1_rate"
     */
    public function testPropertyTax1Rate()
    {
    }

    /**
     * Test attribute "tax1_amount"
     */
    public function testPropertyTax1Amount()
    {
    }

    /**
     * Test attribute "tax2_name"
     */
    public function testPropertyTax2Name()
    {
    }

    /**
     * Test attribute "tax2_rate"
     */
    public function testPropertyTax2Rate()
    {
    }

    /**
     * Test attribute "tax2_amount"
     */
    public function testPropertyTax2Amount()
    {
    }

    /**
     * Test attribute "total"
     */
    public function testPropertyTotal()
    {
    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {
    }

    /**
     * Test attribute "billed_by"
     */
    public function testPropertyBilledBy()
    {
    }

    /**
     * Test attribute "item_name"
     */
    public function testPropertyItemName()
    {
    }

    /**
     * Test attribute "item_description"
     */
    public function testPropertyItemDescription()
    {
    }
}
