<?php
/**
 * RelationshipsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PracticePanther KISS Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * RelationshipsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RelationshipsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for relationshipsDelete
     *
     * .
     *
     */
    public function testRelationshipsDelete()
    {
    }

    /**
     * Test case for relationshipsGetRelationship
     *
     * .
     *
     */
    public function testRelationshipsGetRelationship()
    {
    }

    /**
     * Test case for relationshipsGetRelationships
     *
     * .
     *
     */
    public function testRelationshipsGetRelationships()
    {
    }

    /**
     * Test case for relationshipsPostAccount
     *
     * .
     *
     */
    public function testRelationshipsPostAccount()
    {
    }

    /**
     * Test case for relationshipsPutRelationship
     *
     * .
     *
     */
    public function testRelationshipsPutRelationship()
    {
    }
}
